version: 0.0
os: linux
files:
  - source: /target/so-image-hosting-deploy-sample.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 120
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 120
  ValidateService:
    - location: scripts/basic_health_check.sh
