version: 0.0
os: linux
files:
  - source: /target/so-image-hosting-deploy-sample.jar
    destination: /tmp/image-hosting.jar
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
