#!/bin/bash

set -e

CATALINA_HOME=/usr/share/service
APPLICATION_JAR=so-image-hosting-deploy-sample.jar

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Copy over to the CATALINA_HOME
cp /tmp/$APPLICATION_JAR $CATALINA_HOME

# Install Java if not yet installed
{ which java; } || { yum -y install java; }

# Create the service init.d script
ln -s $CATALINA_HOME/$APPLICATION_JAR /etc/init.d/image-hosting

# Change permission mode for the service script
chmod 755 /etc/init.d/image-hosting

